services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000" # Fix: Use a list format
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
