---
name: Checks

on: [push] # Trigger when code is pushed

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04 # GitHub Actions runner (Ubuntu 20.04)
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2 # Pulls your repository code

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Docker service
        run: |
          sudo service docker start

      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Run Flake8 linting
        run: docker-compose run --rm app sh -c "flake8"
